---
- name: "Update all packages"
  apt:
    name: "*"
    state: latest
    update_cache: yes

- name: "Install software-properties-common"
  apt:
    name: software-properties-common
    update_cache: yes
  