---
- name: "Install virtualenv"
  pip:
    name: "virtualenv"

- name: "Install molecule"
  pip:
    name: "molecule[lint]"
    virtualenv: molecule

- name: "Install molecule docker"
  pip:
    name: "molecule[docker]"
    virtualenv: molecule