---
- name: "Install virtualenv"
  pip:
    name: "virtualenv"

- name: "Install molecule"
  pip:
    name: "molecule[lint]"
    virtualenv: /opt/virtenv/molecule
    virtualenv_command: /usr/local/bin/virtualenv

- name: "Install molecule docker"
  pip:
    name: "molecule[docker]"
    virtualenv: /opt/virtenv/molecule
    virtualenv_command: /usr/local/bin/virtualenv