---
- name: "Install virtualenv"
  pip:
    name: "virtualenv"

- name: "Install molecule requirement python3-pip"
  apt: 
    name: libssl-dev

- name: "Install yamllint"
  apt: 
    name: yamllint

- name: "Install molecule"
  pip:
    name: "molecule[lint]"
    virtualenv: /opt/virtenv/molecule
    virtualenv_command: /usr/local/bin/virtualenv

- name: "Install molecule docker"
  pip:
    name: "molecule[docker]"
    virtualenv: /opt/virtenv/molecule
    virtualenv_command: /usr/local/bin/virtualenv