---
#- name: "Install virtualenv"
#  pip:
#    name: "virtualenv"

- name: "Install molecule requirement python3-pip"
  apt: 
    name: libssl-dev

- name: "Install yamllint"
  apt: 
    name: yamllint

- name: "Upgrade setuptools"
  pip:
    name: "setuptools"
    extra_args: "--user --upgrade"

- name: "Install molecule"
  pip:
    name: "molecule[lint]"
    extra_args: --user
#    virtualenv: /opt/virtenv/molecule
#    virtualenv_command: /usr/local/bin/virtualenv

- name: "Install molecule docker"
  pip:
    name: "molecule[docker]"
    extra_args: --user
#    virtualenv: /opt/virtenv/molecule
#    virtualenv_command: /usr/local/bin/virtualenv