---
  dependency:
    name: galaxy
  driver:
    name: docker
  lint: |
    yamllint .
  platforms:
    - name: instance
      image: ubuntu:18.04
  provisioner:
    name: ansible
    lint: |
      ansible-lint
  verifier:
    name: testinfra
    lint: |
      flake8
  